# Generated by Django 5.2.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(choices=[('DAY', 'Day'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.facility')),
            ],
            options={
                'db_table': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CALLED_OUT', 'Called Out'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('clock_in_at', models.DateTimeField(blank=True, null=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shift_assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hrs_per_resident_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warn_below_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.facility')),
            ],
            options={
                'db_table': 'staffing_configs',
            },
        ),
    ]
