# Generated by Django 5.2.6 on 2026-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='npi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
