# Generated by Django 5.2.6 on 2026-07-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('MEDICARE', 'Medicare'), ('MEDICAID', 'Medicaid'), ('PRIVATE', 'Private'), ('OTHER', 'Other')], max_length=20)),
            ],
            options={
                'db_table': 'insurance_providers',
            },
        ),
        migrations.CreateModel(
            name='ResidentInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number_encrypted', models.CharField(max_length=512)),
                ('group_number', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.insuranceprovider')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
            options={
                'db_table': 'resident_insurance_policies',
            },
        ),
    ]
