# Generated by Django 5.2.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('medicare_covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('medicaid_covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('private_insurance_covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('patient_responsibility_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('due_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('ROOM_BOARD', 'Room & Board'), ('CARE_LEVEL', 'Care Level'), ('MEDICATION', 'Medication'), ('THERAPY', 'Therapy'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_line_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_type', models.CharField(choices=[('MEDICARE', 'Medicare'), ('MEDICAID', 'Medicaid'), ('PRIVATE_INSURANCE', 'Private Insurance'), ('FAMILY', 'Family')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('ACH', 'ACH'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('INSURANCE_DIRECT', 'Insurance Direct')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_token_encrypted', models.CharField(blank=True, max_length=512, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
