# Generated by Django 5.2.6 on 2026-07-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('billing', '0002_invoice_invoicelineitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(db_column='received_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
    ]
