# Generated by Django 5.2.6 on 2026-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentinsurancepolicy',
            name='auth_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
