# Generated by Django 5.2.6 on 2026-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_residentinsurancepolicy_auth_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_level', models.CharField(max_length=50, unique=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
