# Generated by Django 5.2.6 on 2026-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='bed_id',
        ),
    ]
