# Generated by Django 5.2.6 on 2026-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='loc_tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], default='Tier 1', max_length=10),
        ),
    ]
