# Generated by Django 5.2.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_remove_admission_facility_id_remove_resident_bed_id'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.bed'),
        ),
    ]
