# Generated by Django 5.2.6 on 2026-07-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_admission_facility_resident_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='has_dnr',
            field=models.BooleanField(default=False),
        ),
    ]
