# Generated by Django 5.2.6 on 2026-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_resident_has_dnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
