# Generated by Django 5.2.6 on 2026-07-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_admission_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='referral_facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='referral_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='referred_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
