# Generated by Django 5.2.6 on 2026-07-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_resident_referral_facility_resident_referral_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='consent_file',
            field=models.FileField(blank=True, null=True, upload_to='consents/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='consent_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('esignature', 'e-Signature'), ('upload', 'Upload')], max_length=50, null=True),
        ),
    ]
