# Generated by Django 5.2.6 on 2026-07-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_npi'),
        ('residents', '0007_admission_consent_file_admission_consent_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admitting_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_residents_as_nurse', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='admission',
            name='admitting_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_residents_as_physician', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='admission',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
