# Generated by Django 5.2.6 on 2026-07-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_loc_tier'),
        ('residents', '0008_admission_admitting_nurse_and_more'),
    ]

    operations = [
    ]
