# Generated by Django 5.2.6 on 2026-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_merge_20260720_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='payer_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Resident ID'),
        ),
        migrations.AlterModelTable(
            name='resident',
            table=None,
        ),
    ]
