
# Generated by Django 5.2.6 on 2026-07-15 12:47
import django.db.models.deletion
from django.conf import settings
# Generated by Django 5.2.6 on 2026-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentCareLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Overridden', 'Overridden')], max_length=20)),
                ('previous_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('new_tier', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_actions', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_history', to='residents.resident')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PROGRESS_NOTE', 'Progress Note'), ('DIAGNOSIS', 'Diagnosis'), ('LAB_RESULT', 'Lab Result')], max_length=50)),
                ('description', models.TextField()),
                ('recorded_by', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
            options={
                'db_table': 'clinical_records',
            },
        ),
        migrations.CreateModel(
            name='PreAdmissionScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=20)),
                ('screened_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
            options={
                'db_table': 'pre_admission_screenings',
            },
        ),
    ]
