# Generated by Django 5.2.6 on 2026-07-14 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('assessment_type', models.CharField(default='initial', max_length=50)),
                ('total_adl_score', models.IntegerField(default=0)),
                ('adl_bed_mobility', models.IntegerField(default=0)),
                ('adl_transfer', models.IntegerField(default=0)),
                ('adl_locomotion', models.IntegerField(default=0)),
                ('adl_dressing', models.IntegerField(default=0)),
                ('adl_eating', models.IntegerField(default=0)),
                ('adl_toilet_use', models.IntegerField(default=0)),
                ('adl_personal_hygiene', models.IntegerField(default=0)),
                ('adl_bathing', models.IntegerField(default=0)),
                ('loc_tier', models.CharField(blank=True, max_length=20, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='residents.resident')),
            ],
        ),
        migrations.CreateModel(
            name='LOCClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_score', models.IntegerField()),
                ('suggested_loc', models.CharField(max_length=50)),
                ('final_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loc_classification', to='medical.assessment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LOCClassificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loc_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medical.locclassification')),
            ],
        ),
    ]
