# Generated by Django 5.2.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('medical', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ADL', 'ADL'), ('IADL', 'IADL'), ('BRADEN', 'Braden'), ('MORSE', 'Morse')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assessment_metrics',
            },
        ),
        migrations.CreateModel(
            name='CareGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ACHIEVED', 'Achieved'), ('NOT_MET', 'Not Met')], max_length=20)),
            ],
            options={
                'db_table': 'care_goals',
            },
        ),
        migrations.CreateModel(
            name='CareIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'care_interventions',
            },
        ),
        migrations.CreateModel(
            name='CareLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(choices=[('INDEPENDENT_LIVING', 'Independent Living'), ('ASSISTED_LIVING', 'Assisted Living'), ('MEMORY_CARE', 'Memory Care'), ('SKILLED_NURSING', 'Skilled Nursing'), ('HOSPICE', 'Hospice')], max_length=30, unique=True)),
                ('level_name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'care_levels',
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('DISCONTINUED', 'Discontinued')], max_length=20)),
                ('significant_change_flag', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'care_plans',
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('is_abnormal_flagged', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_tasks',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('FALL', 'Fall'), ('MEDICATION_ERROR', 'Medication Error'), ('ALTERCATION', 'Altercation'), ('SKIN_TEAR', 'Skin Tear')], max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('chart_lock_trigger', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'incident_severities',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'incident_timelines',
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ADMINISTERED', 'Administered'), ('REFUSED', 'Refused'), ('HELD', 'Held'), ('NOT_AVAILABLE', 'Not Available')], max_length=20)),
                ('is_clinically_justified', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_logs',
            },
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=30)),
                ('frequency', models.CharField(max_length=100)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('ON_HOLD', 'On Hold')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medication_orders',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medication_schedules',
            },
        ),
        migrations.CreateModel(
            name='ResidentCareLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resident_care_level_history',
            },
        ),
        migrations.CreateModel(
            name='SlaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_window_hrs', models.IntegerField()),
            ],
            options={
                'db_table': 'sla_configs',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.SmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.SmallIntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.SmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.SmallIntegerField(blank=True, null=True)),
                ('temperature_fahrenheit', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_scale', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='preadmissionscreening',
            name='screened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adl_total_score', models.IntegerField()),
                ('is_overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
                ('confirmed_care_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medical.carelevel')),
                ('suggested_care_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medical.carelevel')),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.assessment')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.assessmentmetric')),
            ],
            options={
                'db_table': 'assessment_details',
            },
        ),
        migrations.CreateModel(
            name='CareLevelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('care_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.carelevel')),
            ],
            options={
                'db_table': 'care_level_rates',
            },
        ),
    ]
