# Generated by Django 5.2.6 on 2026-07-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('initial', 'Initial Assessment'), ('periodic', 'Periodic Assessment'), ('quarterly', 'Quarterly Assessment'), ('annual', 'Annual Assessment'), ('change_of_condition', 'Change of Condition')], default='initial', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='care_level',
            field=models.CharField(blank=True, choices=[('independent', 'Independent'), ('minimal_assist', 'Minimal Assist'), ('moderate_assist', 'Moderate Assist'), ('maximum_assist', 'Maximum Assist'), ('total_care', 'Total Care')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='clinical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='cognitive_status',
            field=models.CharField(blank=True, choices=[('alert_oriented', 'Alert & Oriented'), ('alert_oriented_x1', 'Alert & Oriented x1'), ('alert_oriented_x2', 'Alert & Oriented x2'), ('alert_oriented_x3', 'Alert & Oriented x3'), ('confused', 'Confused'), ('lethargic', 'Lethargic'), ('obtunded', 'Obtunded'), ('stupor', 'Stupor'), ('coma', 'Coma')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_adl_score',
            field=models.IntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_iadl_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_adl_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_iadl_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='medical.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='category',
            field=models.CharField(choices=[('adl', 'Activities of Daily Living'), ('iadl', 'Instrumental ADL'), ('vital_sign', 'Vital Sign')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='item_key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdetail',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdiagnosis',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentdiagnosis',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdiagnosis',
            name='diagnosis_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentdiagnosis',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentdiagnosis',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='max_adl_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='min_adl_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carelevel',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
