# Generated by Django 5.2.6 on 2026-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregoal',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='measure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
