# Generated by Django 5.2.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('medical', '0002_assessmentmetric_caregoal_careintervention_carelevel_and_more'),
        ('residents', '0002_remove_admission_facility_id_remove_resident_bed_id'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelevelrate',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.facility'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
        migrations.AddField(
            model_name='careintervention',
            name='care_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.careplan'),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='care_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.careplan'),
        ),
        migrations.AddField(
            model_name='caretask',
            name='assigned_cna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='caretask',
            name='care_intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.careintervention'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical.incidentseverity'),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.incident'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='administered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_meds', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_meds', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='prescribed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicationorder'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicationorder'),
        ),
        migrations.AddField(
            model_name='residentcarelevelhistory',
            name='care_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.carelevel'),
        ),
        migrations.AddField(
            model_name='residentcarelevelhistory',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.incidentseverity'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
    ]
