# Generated by Django 5.2.6 on 2026-07-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('medical', '0003_carelevelrate_facility_careplan_resident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessed_by',
            field=models.ForeignKey(db_column='assessed_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='recorded_by',
            field=models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='administered_by',
            field=models.ForeignKey(db_column='administered_by', on_delete=django.db.models.deletion.PROTECT, related_name='administered_meds', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, db_column='witnessed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_meds', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='medicationorder',
            name='prescribed_by',
            field=models.ForeignKey(db_column='prescribed_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='preadmissionscreening',
            name='screened_by',
            field=models.ForeignKey(db_column='screened_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='recorded_by',
            field=models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='ChartLockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_by_system', models.BooleanField(default=True)),
                ('unlock_reason', models.TextField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.incident')),
                ('unlocked_by', models.ForeignKey(blank=True, db_column='unlocked_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
            options={
                'db_table': 'chart_lock_events',
            },
        ),
    ]
