# Generated by Django 5.2.6 on 2026-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_assessment_assessed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='record_type',
            field=models.CharField(choices=[('PROGRESS_NOTE', 'Progress Note'), ('DIAGNOSIS', 'Diagnosis'), ('LAB_RESULT', 'Lab Result'), ('ALLERGY', 'Allergy')], max_length=50),
        ),
    ]
