# Generated by Django 5.2.6 on 2026-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_clinicalrecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='preadmissionscreening',
            name='acuity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='clinical_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='compliance_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='estimated_care_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preadmissionscreening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
