# Generated by Django 5.2.6 on 2026-07-20 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_preadmissionscreening_acuity_level_and_more'),
        ('residents', '0010_resident_payer_source_resident_resident_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='residents.resident'),
        ),
        migrations.CreateModel(
            name='LOCClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_score', models.IntegerField()),
                ('suggested_loc', models.CharField(max_length=50)),
                ('final_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=20)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loc_classification', to='medical.assessment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loc_classifications',
            },
        ),
        migrations.CreateModel(
            name='LOCClassificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loc_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='medical.locclassification')),
            ],
            options={
                'db_table': 'loc_classification_history',
            },
        ),
    ]
